Issue50 missing address
nansencenter/django-geo-spaas-processing pull request #51
Opened 2021-03-31 10:07 UTC by azamifarda

close #50

2021-04-06 07:22 UTC, aperrin66 requested changes

2021-04-06 07:22 UTC, aperrin66 commented on geospaas_processing/downloaders.py
> +                    if self.save_path:
```suggestion
                    if file_name and self.save_path:
```
Just a precaution.

2021-04-06 07:22 UTC, aperrin66 commented on geospaas_processing/downloaders.py
> +                            )
```suggestion
                        )
```

2021-04-06 07:36 UTC, aperrin66 approved these changes

2021-04-09 06:56 UTC, akorosov approved these changes
Looks good

2021-04-09 06:56 UTC, merged